### ISSUE TITLE
[Feat] README.md 갱신하기

### ISSUE THREAD

**Issue by hyo-choi** [hyo-choi/wanted-pre-onboarding#8]
# TO-DO
## README.md
- [x] [Chromatic 주소](https://main--61df0caa24fa0d004afe84fa.chromatic.com/), [Netlify 주소](https://pre-onboarding-hyo-choi.netlify.app/) 둘 다 쓰기
  - [x] 최종 deploy하기([아래 코멘트 참고](https://github.com/hyo-choi/wanted-pre-onboarding/issues/8#issuecomment-1011436928))
- [x] Netlify Badge 달기
[![Netlify Status](https://api.netlify.com/api/v1/badges/9bbb7ca1-7465-40de-9ebb-ec2b402af0d6/deploy-status)](https://app.netlify.com/sites/pre-onboarding-hyo-choi/deploys)
- [x] Typescript 사용 가능 여부 문의하고 작성했다는 것 작성
- [x] 디렉토리 구조도 같은 것 넣을지 말지...
- [x] ~~새로 배운 것 작성?~~
  -> 따로 작성하는 대신 issue에 간단하게 코멘트 남기기로
  - draggable, touchEvent
  - Storybook viewport 설정 방법
  - Netlify로 배포하는 법
## 제출 전 재차 확인할 것
- 링크: [모집 공고](https://www.wanted.co.kr/events/pre_onboarding_course_6), [제출 안내](https://www.wanted.co.kr/wd/92398), [과제 요구사항](https://www.notion.so/X-9e8ff10dd1614112a81797219b7e6742)
- [x] 원티드 이력서 확인
  - [x] 링크에 github, 배포 링크 포함
- [x] 집중육성전형 문서 첨부

**Comment by hyo-choi** [comment]
main branch에 자잘하게 push하게 될 일이 많을 듯해 Netlify auto publish를 중단해둠.
deploy가 필요할 때 Trigger deploy 해주거나 자잘한 업데이트가 끝난 뒤 Start auto publishing 할 것.

**Comment by hyo-choi** [comment]
- [Linux tree 명령어 사용법](https://www.lesstif.com/lpt/linux-tree-54952142.html)
```bash
.
├── public
└── src
    ├── Icons
    ├── components
    │   ├── MenuItem
    │   ├── NavBar
    │   ├── SlideItem
    │   └── Slider
    ├── constants
    ├── hooks
    └── utils
```
